length = float(input('Enter the length of cuboid :'))
width = float(input('Enter the width of cuboid :'))
height = float(input('Enter the height of cuboid :'))
print('Volume of cuboid =',length*width*height)
print('Total Surface Area =',2*(length*width+width*height+height*length))